### ISSUE TITLE
Shield utility only defends against attack damage

### ISSUE THREAD

**Issue by insertStringHere** [insertStringHere/MineBound#126]
Shield utility should defend against all forms of damage, not just attack

**Comment by MattKirchh** [comment]
Should it even defend against starving damage and falling out of the world damage?

**Comment by MattKirchh** [comment]
> Should it even defend against starving damage and falling out of the world damage?

The reason I specifically point out these two damage sources is because starvation damage has the `bypassMagic` property and the falling out of the world damage source has the `bypassInvul` property. These are properties that other mods could also use for custom damage sources and blocking those damage sources may lead to undesirable interactions.
